/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const LegalAdviceLazyImport = createFileRoute('/legal-advice')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const LegalAdviceLazyRoute = LegalAdviceLazyImport.update({
  id: '/legal-advice',
  path: '/legal-advice',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/legal-advice.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/legal-advice': {
      id: '/legal-advice'
      path: '/legal-advice'
      fullPath: '/legal-advice'
      preLoaderRoute: typeof LegalAdviceLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/legal-advice': typeof LegalAdviceLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/legal-advice': typeof LegalAdviceLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/legal-advice': typeof LegalAdviceLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/legal-advice'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/legal-advice'
  id: '__root__' | '/' | '/legal-advice'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LegalAdviceLazyRoute: typeof LegalAdviceLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LegalAdviceLazyRoute: LegalAdviceLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/legal-advice"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/legal-advice": {
      "filePath": "legal-advice.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
